name: Deploiement d'un environnement Windows Virtual Desktop
on: workflow_dispatch

env:
  #Variables plateforme 
  AZURE_RG: "RG-WVD-GH-00" # Nom du groupe de ressources
  AZURE_LOC: "northeurope" # Region Azure cible
  DEPLOYNAME: "Rollup-000" # Nom du déploiement

  #Variables WVD
  HOSTPOOLS_NAME: "HP-CICD-01" #Nom du Hostpool

jobs:

  Test-Arm:
    runs-on: ubuntu-20.04
    name: Test-ARM
    

    steps:

      - name: Generation du Token Expiration Time
        shell: pwsh
        run: |
          $Expiration=$((get-date).ToUniversalTime().AddHours(2).ToString('yyyy-MM-ddTHH:mm:ss.fffffffZ'))
          echo "::set-output name=outexp::$($Expiration)"
        id: var_exp   

      - name: Test de la variable Token Expiration Time
        shell: pwsh
        run: |
          echo "Le jeton généré est: ${{ steps.var_exp.outputs.outexp }}"

      - name: Download Repo conten
        uses: actions/checkout@v2
